## -----------------------------------------------------------------------------
## Purpose of script: Preprocess patient metadata
##
## Author: Oliver Artz
## Date Created: May 23, 2025
## Email: artzo@mskcc.org
##
## -----------------------------------------------------------------------------

# clear work space -------------------------------------------------------------
# rm(list = ls())
# gc()

# load libraries ---------------------------------------------------------------
options(repos = "https://cran.rstudio.com")
if (!require('pacman')) install.packages('pacman', dependencies = TRUE); library(pacman)

p_load(tidyverse, data.table, here)

# set parameters ---------------------------------------------------------------
project_root <- here()
project_folder <- "20250521_TMBH_acquisition"

# load data --------------------------------------------------------------------
# generated by Oliver
patient_meta <- fread(paste0(
  project_root, "/",
  project_folder,
  "/data/metadata/20250521_patient_meta.csv"))

# wrangle ----------------------------------------------------------------------
patient_meta_mod <- patient_meta %>% clean_names()

# add impact baseline version
patient_meta_mod <- patient_meta_mod %>% 
  mutate(baseline_impact_version = str_sub(impact_baseline, -3, -1))

# remove mrn
patient_meta_mod <- patient_meta_mod %>% 
  select(-mrn)

# # make long
# patient_meta_mod_long <- patient_meta_mod %>%
#   select(patient_id, guardant_baseline, guardant_progression, acquired_tmbh, baseline_impact_version) %>% 
#   pivot_longer(cols = c(guardant_baseline, guardant_progression),
#                names_to = "sample_status",
#                values_to = "accession_id") %>% 
#   mutate(sample_status = str_remove(sample_status, "guardant_"))

# export -----------------------------------------------------------------------
write.table(
  patient_meta_mod,
  paste0(project_root, "/", project_folder, "/data/processed/003_patient_meta_mod.txt"),
  sep = "\t",
  row.names = FALSE,
  col.names = TRUE,
  quote = FALSE
)

# cleanup ----------------------------------------------------------------------
rm()